version: "3.0"
services:
  mongo:
    image: "mongo"
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017

  swagger:
    image: "swaggerapi/swagger-editor"
    ports:
      - 80:8080

